<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 10.11.2017
 * Time: 12:49
 */

namespace egor260890\sort\widgets\gridview;


use yii\grid\ActionColumn;
use yii\helpers\Html;
use egor260890\sort\Assets;

class MoveColumn extends ActionColumn
{

    public $template='<div class="btn-gr">{prev} {next}</div> <div class="btn-gr">{first} {last}</div>';

    public $pjaxContainerSelector='#pjax-content';

    public $buttons=[];

    public $method='';

    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    public function init()
    {
        Assets::register(\Yii::$app->getView(),\yii\web\View::POS_END);
        $this->registerPjaxContainer();
        parent::init(); // TODO: Change the autogenerated stub
    }

    protected function initDefaultButtons()
    {
        $this->initDefaultButton('first', 'fa-level-up',['title'=>'В начало']);
        $this->initDefaultButton('prev', 'fa-arrow-circle-o-up',['title'=>'Выше']);
        $this->initDefaultButton('next', 'fa-arrow-circle-o-down',['title'=>'Ниже']);
        $this->initDefaultButton('last', 'fa-level-down',['title'=>'Конец']);
    }

    public function initDefaultButton($name, $iconName, $additionalOptions = [])
    {
        $button=function ($url,$model)use($additionalOptions,$name,$iconName){
            return Html::button(Html::tag('span', '',['class'=>"fa $iconName"]),['class'=>'move-button' ,'title'=>$additionalOptions['title'],'value'=>\yii\helpers\Url::to([$this->method,'id'=>$model->id,'action'=>$name])]);

        };
        $this->buttons[$name]=$button;
    }

    private function registerPjaxContainer(){
        $script="setPjaxContainer('".$this->pjaxContainerSelector."');";
        \Yii::$app->getView()->registerJs($script,\yii\web\View::POS_END);
    }

}

